/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package dhs.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Patient service. Represents a row in the &quot;DHS_Patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link dhs.common.service.model.impl.PatientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link dhs.common.service.model.impl.PatientImpl}.
 * </p>
 *
 * @author sandip.patel
 * @see Patient
 * @see dhs.common.service.model.impl.PatientImpl
 * @see dhs.common.service.model.impl.PatientModelImpl
 * @generated
 */
@ProviderType
public interface PatientModel extends BaseModel<Patient> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patient model instance should use the {@link Patient} interface instead.
	 */

	/**
	 * Returns the primary key of this patient.
	 *
	 * @return the primary key of this patient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patient.
	 *
	 * @param primaryKey the primary key of this patient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patient ID of this patient.
	 *
	 * @return the patient ID of this patient
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this patient.
	 *
	 * @param patientId the patient ID of this patient
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the lr user ID of this patient.
	 *
	 * @return the lr user ID of this patient
	 */
	public long getLrUserId();

	/**
	 * Sets the lr user ID of this patient.
	 *
	 * @param lrUserId the lr user ID of this patient
	 */
	public void setLrUserId(long lrUserId);

	/**
	 * Returns the lr user uuid of this patient.
	 *
	 * @return the lr user uuid of this patient
	 */
	public String getLrUserUuid();

	/**
	 * Sets the lr user uuid of this patient.
	 *
	 * @param lrUserUuid the lr user uuid of this patient
	 */
	public void setLrUserUuid(String lrUserUuid);

	/**
	 * Returns the msp no of this patient.
	 *
	 * @return the msp no of this patient
	 */
	@AutoEscape
	public String getMspNo();

	/**
	 * Sets the msp no of this patient.
	 *
	 * @param mspNo the msp no of this patient
	 */
	public void setMspNo(String mspNo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(dhs.common.service.model.Patient patient);

	@Override
	public int hashCode();

	@Override
	public CacheModel<dhs.common.service.model.Patient> toCacheModel();

	@Override
	public dhs.common.service.model.Patient toEscapedModel();

	@Override
	public dhs.common.service.model.Patient toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}